In [ ]:
!pip -q install torch torchvision pillow pandas tqdm jiwer evaluate
!pip -q install "transformers>=4.45.0" accelerate qwen-vl-utils

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 102.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.3/596.3 kB 51.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 117.1 MB/s eta 0:00:00

In [ ]:
import os
import re
import glob
import pandas as pd
from PIL import Image
from tqdm import tqdm

import torch
import evaluate
from jiwer import wer

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
BASE_FOLDER = "/content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset"
TRAIN_FOLDER = BASE_FOLDER + "/Training"
VAL_FOLDER = BASE_FOLDER + "/Validation"
TEST_FOLDER = BASE_FOLDER + "/Testing"

In [ ]:
df_train = pd.read_csv(TRAIN_FOLDER + "/training_labels.csv")
df_train.drop(columns=["GENERIC_NAME"], inplace=True)
df_train

         IMAGE MEDICINE_NAME
0        0.png         Aceta
1        1.png         Aceta
2        2.png         Aceta
3        3.png         Aceta
4        4.png         Aceta
...        ...           ...
3115  3115.png       Zithrin
3116  3116.png       Zithrin
3117  3117.png       Zithrin
3118  3118.png       Zithrin
3119  3119.png       Zithrin

[3120 rows x 2 columns]

In [ ]:
df_val = pd.read_csv(VAL_FOLDER + "/validation_labels.csv")
df_val.drop(columns=["GENERIC_NAME"], inplace=True)
df_val

       IMAGE MEDICINE_NAME
0      0.png         Aceta
1      1.png         Aceta
2      2.png         Aceta
3      3.png         Aceta
4      4.png         Aceta
..       ...           ...
775  775.png       Zithrin
776  776.png       Zithrin
777  777.png       Zithrin
778  778.png       Zithrin
779  779.png       Zithrin

[780 rows x 2 columns]

In [ ]:
df_test = pd.read_csv(TEST_FOLDER + "/testing_labels.csv")
df_test.drop(columns=["GENERIC_NAME"], inplace=True)
df_test

       IMAGE MEDICINE_NAME
0      0.png         Aceta
1      1.png         Aceta
2      2.png         Aceta
3      3.png         Aceta
4      4.png         Aceta
..       ...           ...
775  775.png       Zithrin
776  776.png       Zithrin
777  777.png       Zithrin
778  778.png       Zithrin
779  779.png       Zithrin

[780 rows x 2 columns]

In [ ]:
import torch
from transformers import AutoProcessor, Qwen2VLForConditionalGeneration
from qwen_vl_utils import process_vision_info

MODEL_NAME = "Qwen/Qwen2-VL-2B-Instruct"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 1
MAX_NEW_TOKENS = 128

In [ ]:
def normalize_text(s: str) -> str:
    s = str(s).strip().lower()
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r"[^\w\s]", "", s)
    return s

processor = AutoProcessor.from_pretrained(MODEL_NAME, trust_remote_code=True)
model = Qwen2VLForConditionalGeneration.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto",
    trust_remote_code=True
)
model.eval()

cer_metric = evaluate.load("cer")

def qwen2vl_ocr_one(pil_img: Image.Image) -> str:
    """Run OCR with Qwen2-VL by prompting it to extract text."""
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": pil_img},
                {"type": "text", "text": "Extract ALL text from this image exactly as it appears. Preserve line breaks."}
            ],
        }
    ]

    prompt = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    image_inputs, video_inputs = process_vision_info(messages)

    inputs = processor(
        text=[prompt],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    ).to(model.device)

    with torch.no_grad():
        output_ids = model.generate(**inputs, max_new_tokens=MAX_NEW_TOKENS)

    # remove prompt tokens
    gen_ids = output_ids[:, inputs["input_ids"].shape[1]:]
    out = processor.batch_decode(gen_ids, skip_special_tokens=True)[0]
    return out.strip()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

The image processor of type `Qwen2VLImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/729 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/272 [00:00<?, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

In [ ]:
from PIL import Image
import os

TRAIN_IMG_DIR = os.path.join(TRAIN_FOLDER, "training_words")
VAL_IMG_DIR   = os.path.join(VAL_FOLDER,   "validation_words")
TEST_IMG_DIR  = os.path.join(TEST_FOLDER,  "testing_words")

SPLIT_TO_DIR = {
    "train": TRAIN_IMG_DIR,
    "val":   VAL_IMG_DIR,
    "test":  TEST_IMG_DIR,
}

def load_rgb(img_name: str, split_name: str):
    img_path = os.path.join(SPLIT_TO_DIR[split_name], img_name)
    return Image.open(img_path).convert("RGB")


def evaluate_split(df: pd.DataFrame, split_name: str, limit: int | None = None):
    if len(df) == 0:
        return None, None

    if limit is not None:
        df = df.iloc[:limit].copy()

    preds_raw = []
    gts_raw = df["MEDICINE_NAME"].astype(str).tolist()

    for start in tqdm(range(0, len(df), BATCH_SIZE), desc=f"Qwen2-VL {split_name}"):
        batch = df.iloc[start:start+BATCH_SIZE]
        for img_name in batch["IMAGE"].tolist():
            img = load_rgb(img_name, split_name)
            preds_raw.append(qwen2vl_ocr_one(img))

    out = df.copy()
    out["split"] = split_name
    out["pred_raw"] = preds_raw
    out["pred_norm"] = out["pred_raw"].apply(normalize_text)
    out["gt_norm"] = out["MEDICINE_NAME"].apply(normalize_text)

    exact_match = (out["pred_norm"] == out["gt_norm"]).mean()
    cer_value = cer_metric.compute(predictions=out["pred_norm"].tolist(),
                                   references=out["gt_norm"].tolist())
    wer_value = wer(out["gt_norm"].tolist(), out["pred_norm"].tolist())

    metrics = {
        "split": split_name,
        "samples": len(out),
        "exact_match": float(exact_match),
        "cer": float(cer_value),
        "wer": float(wer_value),
    }
    return metrics, out


LIMIT = None

all_metrics = []
all_outputs = []

for split_name, df in [("train", df_train), ("val", df_val), ("test", df_test)]:
    metrics, out = evaluate_split(df, split_name, limit=LIMIT)
    if metrics is None:
        print(f"[WARN] No samples found for split: {split_name}")
        continue
    all_metrics.append(metrics)
    all_outputs.append(out)

metrics_df = pd.DataFrame(all_metrics)
print("\n===== SUMMARY =====")
print(metrics_df.to_string(index=False))


for out in all_outputs:
    split = out["split"].iloc[0]
    out_csv = os.path.join(BASE_FOLDER, f"qwen2vl_predictions_{split}.csv")
    out.to_csv(out_csv, index=False)
    print("Saved:", out_csv)

combined = pd.concat(all_outputs, ignore_index=True)
combined_csv = os.path.join(BASE_FOLDER, "qwen2vl_predictions_all_splits.csv")
combined.to_csv(combined_csv, index=False)
print("Saved:", combined_csv)

metrics_csv = os.path.join(BASE_FOLDER, "qwen2vl_metrics_summary.csv")
metrics_df.to_csv(metrics_csv, index=False)
print("Saved:", metrics_csv)

Qwen2-VL train:   0%|          | 0/3120 [00:00<?, ?it/s]
Qwen2-VL train:   0%|          | 1/3120 [00:18<15:37:36, 18.04s/it]
Qwen2-VL train:   0%|          | 2/3120 [00:18<6:43:51,  7.77s/it]
Qwen2-VL train:   0%|          | 3/3120 [00:19<3:56:30,  4.55s/it]
Qwen2-VL train:   0%|          | 4/3120 [00:19<2:34:18,  2.97s/it]
Qwen2-VL train:   0%|          | 5/3120 [00:20<1:49:53,  2.12s/it]
Qwen2-VL train:   0%|          | 6/3120 [00:21<1:24:27,  1.63s/it]
Qwen2-VL train:   0%|          | 7/3120 [00:21<1:06:27,  1.28s/it]
Qwen2-VL train:   0%|          | 8/3120 [00:22<56:14,  1.08s/it]
Qwen2-VL train:   0%|          | 9/3120 [00:22<47:32,  1.09it/s]
Qwen2-VL train:   0%|          | 10/3120 [00:23<41:33,  1.25it/s]
Qwen2-VL train:   0%|          | 11/3120 [00:24<37:46,  1.37it/s]
Qwen2-VL train:   0%|          | 12/3120 [00:24<34:41,  1.49it/s]
Qwen2-VL train:   0%|          | 13/3120 [00:25<32:04,  1.61it/s]
Qwen2-VL train:   0%|          | 14/3120 [00:25<30:11,  1.71it/s]
Qwen2-VL train:   0%|          | 15/3120 [00:26<30:48,  1.68it/s]
Qwen2-VL train:   1%|          | 16/3120 [00:26<31:16,  1.65it/s]
Qwen2-VL train:   1%|          | 17/3120 [00:27<33:58,  1.52it/s]
Qwen2-VL train:   1%|          | 18/3120 [00:28<32:21,  1.60it/s]
Qwen2-VL train:   1%|          | 19/3120 [00:28<30:50,  1.68it/s]
Qwen2-VL train:   1%|          | 20/3120 [00:29<32:08,  1.61it/s]
Qwen2-VL train:   1%|          | 21/3120 [00:29<31:47,  1.62it/s]
Qwen2-VL train:   1%|          | 22/3120 [00:30<31:31,  1.64it/s]
Qwen2-VL train:   1%|          | 23/3120 [00:31<31:41,  1.63it/s]
Qwen2-VL train:   1%|          | 24/3120 [00:31<30:27,  1.69it/s]
Qwen2-VL train:   1%|          | 25/3120 [00:32<30:42,  1.68it/s]
Qwen2-VL train:   1%|          | 26/3120 [00:32<30:27,  1.69it/s]
Qwen2-VL train:   1%|          | 27/3120 [00:33<31:13,  1.65it/s]
Qwen2-VL train:   1%|          | 28/3120 [00:34<32:45,  1.57it/s]
Qwen2-VL train:   1%|          | 29/3120 [00:34<32:24,  1.59it/s]
Qwen2-VL train:   1%|          | 30/3120 [00:35<33:22,  1.54it/s]
Qwen2-VL train:   1%|          | 31/3120 [00:36<31:15,  1.65it/s]
Qwen2-VL train:   1%|          | 32/3120 [00:36<29:46,  1.73it/s]
Qwen2-VL train:   1%|          | 33/3120 [00:37<29:11,  1.76it/s]
Qwen2-VL train:   1%|          | 34/3120 [00:37<28:27,  1.81it/s]
Qwen2-VL train:   1%|          | 35/3120 [00:38<29:08,  1.76it/s]
Qwen2-VL train:   1%|          | 36/3120 [00:38<29:57,  1.72it/s]
Qwen2-VL train:   1%|          | 37/3120 [00:39<30:41,  1.67it/s]
Qwen2-VL train:   1%|          | 38/3120 [00:40<32:13,  1.59it/s]
Qwen2-VL train:   1%|▏         | 39/3120 [00:40<30:41,  1.67it/s]
Qwen2-VL train:   1%|▏         | 40/3120 [00:41<31:37,  1.62it/s]
Qwen2-VL train:   1%|▏         | 41/3120 [00:42<31:43,  1.62it/s]
Qwen2-VL train:   1%|▏         | 42/3120 [00:42<30:00,  1.71it/s]
Qwen2-VL train:   1%|▏         | 43/3120 [00:43<29:00,  1.77it/s]
Qwen2-VL train:   1%|▏         | 44/3120 [00:43<27:07,  1.89it/s]
Qwen2-VL train:   1%|▏         | 45/3120 [00:44<39:25,  1.30it/s]
Qwen2-VL train:   1%|▏         | 46/3120 [00:45<35:12,  1.46it/s]
Qwen2-VL train:   2%|▏         | 47/3120 [00:45<32:56,  1.55it/s]
Qwen2-VL train:   2%|▏         | 48/3120 [00:49<1:13:42,  1.44s/it]
Qwen2-VL train:   2%|▏         | 49/3120 [00:49<58:25,  1.14s/it]
Qwen2-VL train:   2%|▏         | 50/3120 [00:50<51:17,  1.00s/it]
Qwen2-VL train:   2%|▏         | 51/3120 [00:50<43:45,  1.17it/s]
Qwen2-VL train:   2%|▏         | 52/3120 [00:51<40:28,  1.26it/s]
Qwen2-VL train:   2%|▏         | 53/3120 [00:51<36:19,  1.41it/s]
Qwen2-VL train:   2%|▏         | 54/3120 [00:52<32:51,  1.56it/s]
Qwen2-VL train:   2%|▏         | 55/3120 [00:52<30:50,  1.66it/s]
Qwen2-VL train:   2%|▏         | 56/3120 [00:53<29:50,  1.71it/s]
Qwen2-VL train:   2%|▏         | 57/3120 [00:54<28:57,  1.76it/s]
Qwen2-VL train:   2%|▏         | 58/3120 [00:54<28:52,  1.77it/s]
Qwen2-VL train:   2%|▏         | 59/3120 [00:55<27:51,  1.83it/s]
Qwen2-VL train:   2%|▏         | 60/3120 [00:55<26:48,  1.90it/s]
Qwen2-VL train:   2%|▏         | 61/3120 [00:56<37:31,  1.36it/s]
Qwen2-VL train:   2%|▏         | 62/3120 [00:57<33:51,  1.51it/s]
Qwen2-VL train:   2%|▏         | 63/3120 [00:57<30:13,  1.69it/s]
Qwen2-VL train:   2%|▏         | 64/3120 [00:58<30:28,  1.67it/s]
Qwen2-VL train:   2%|▏         | 65/3120 [00:58<28:23,  1.79it/s]
Qwen2-VL train:   2%|▏         | 66/3120 [00:59<27:54,  1.82it/s]
Qwen2-VL train:   2%|▏         | 67/3120 [01:00<39:19,  1.29it/s]
Qwen2-VL train:   2%|▏         | 68/3120 [01:01<35:02,  1.45it/s]
Qwen2-VL train:   2%|▏         | 69/3120 [01:01<32:51,  1.55it/s]
Qwen2-VL train:   2%|▏         | 70/3120 [01:02<31:43,  1.60it/s]
Qwen2-VL train:   2%|▏         | 71/3120 [01:02<29:42,  1.71it/s]
Qwen2-VL train:   2%|▏         | 72/3120 [01:03<30:40,  1.66it/s]
Qwen2-VL train:   2%|▏         | 73/3120 [01:03<29:37,  1.71it/s]
Qwen2-VL train:   2%|▏         | 74/3120 [01:04<32:36,  1.56it/s]
Qwen2-VL train:   2%|▏         | 75/3120 [01:05<31:43,  1.60it/s]
Qwen2-VL train:   2%|▏         | 76/3120 [01:05<31:49,  1.59it/s]
Qwen2-VL train:   2%|▏         | 77/3120 [01:07<42:23,  1.20it/s]
Qwen2-VL train:   2%|▎         | 78/3120 [01:07<36:41,  1.38it/s]
Qwen2-VL train:   3%|▎         | 79/3120 [01:08<34:01,  1.49it/s]
Qwen2-VL train:   3%|▎         | 80/3120 [01:08<32:56,  1.54it/s]
Qwen2-VL train:   3%|▎         | 81/3120 [01:09<33:17,  1.52it/s]
Qwen2-VL train:   3%|▎         | 82/3120 [01:10<33:36,  1.51it/s]
Qwen2-VL train:   3%|▎         | 83/3120 [01:11<43:27,  1.16it/s]
Qwen2-VL train:   3%|▎         | 84/3120 [01:12<48:34,  1.04it/s]
Qwen2-VL train:   3%|▎         | 85/3120 [01:13<41:52,  1.21it/s]
Qwen2-VL train:   3%|▎         | 86/3120 [01:13<37:39,  1.34it/s]
Qwen2-VL train:   3%|▎         | 87/3120 [01:14<34:41,  1.46it/s]
Qwen2-VL train:   3%|▎         | 88/3120 [01:14<33:43,  1.50it/s]
Qwen2-VL train:   3%|▎         | 89/3120 [01:15<30:11,  1.67it/s]
Qwen2-VL train:   3%|▎         | 90/3120 [01:16<43:57,  1.15it/s]
Qwen2-VL train:   3%|▎         | 91/3120 [01:17<42:10,  1.20it/s]
Qwen2-VL train:   3%|▎         | 92/3120 [01:18<40:14,  1.25it/s]
Qwen2-VL train:   3%|▎         | 93/3120 [01:19<49:58,  1.01it/s]
Qwen2-VL train:   3%|▎         | 94/3120 [01:20<42:22,  1.19it/s]
Qwen2-VL train:   3%|▎         | 95/3120 [01:20<40:30,  1.24it/s]
Qwen2-VL train:   3%|▎         | 96/3120 [01:23<1:03:19,  1.26s/it]
Qwen2-VL train:   3%|▎         | 97/3120 [01:26<1:30:23,  1.79s/it]
Qwen2-VL train:   3%|▎         | 98/3120 [01:27<1:22:17,  1.63s/it]
Qwen2-VL train:   3%|▎         | 99/3120 [01:29<1:19:45,  1.58s/it]
Qwen2-VL train:   3%|▎         | 100/3120 [01:29<1:06:10,  1.31s/it]
Qwen2-VL train:   3%|▎         | 101/3120 [01:30<55:29,  1.10s/it]
Qwen2-VL train:   3%|▎         | 102/3120 [01:31<48:54,  1.03it/s]
Qwen2-VL train:   3%|▎         | 103/3120 [01:32<55:16,  1.10s/it]
Qwen2-VL train:   3%|▎         | 104/3120 [01:33<59:10,  1.18s/it]
Qwen2-VL train:   3%|▎         | 105/3120 [01:35<1:02:04,  1.24s/it]
Qwen2-VL train:   3%|▎         | 106/3120 [01:35<50:18,  1.00s/it]
Qwen2-VL train:   3%|▎         | 107/3120 [01:36<53:23,  1.06s/it]
Qwen2-VL train:   3%|▎         | 108/3120 [01:38<58:46,  1.17s/it]
Qwen2-VL train:   3%|▎         | 109/3120 [01:39<1:00:41,  1.21s/it]
Qwen2-VL train:   4%|▎         | 110/3120 [01:40<1:02:55,  1.25s/it]
Qwen2-VL train:   4%|▎         | 111/3120 [01:42<1:02:16,  1.24s/it]
Qwen2-VL train:   4%|▎         | 112/3120 [01:42<53:24,  1.07s/it]
Qwen2-VL train:   4%|▎         | 113/3120 [01:44<1:01:51,  1.23s/it]
Qwen2-VL train:   4%|▎         | 114/3120 [01:45<53:54,  1.08s/it]
Qwen2-VL train:   4%|▎         | 115/3120 [01:47<1:11:03,  1.42s/it]
Qwen2-VL train:   4%|▎         | 116/3120 [01:47<58:17,  1.16s/it]
Qwen2-VL train:   4%|▍         | 117/3120 [01:48<50:57,  1.02s/it]
Qwen2-VL train:   4%|▍         | 118/3120 [01:49<45:50,  1.09it/s]
Qwen2-VL train:   4%|▍         | 119/3120 [01:50<52:07,  1.04s/it]
Qwen2-VL train:   4%|▍         | 120/3120 [01:51<44:19,  1.13it/s]
Qwen2-VL train:   4%|▍         | 121/3120 [01:51<38:06,  1.31it/s]
Qwen2-VL train:   4%|▍         | 122/3120 [01:52<35:09,  1.42it/s]
Qwen2-VL train:   4%|▍         | 123/3120 [01:52<34:26,  1.45it/s]
Qwen2-VL train:   4%|▍         | 124/3120 [01:53<41:45,  1.20it/s]
Qwen2-VL train:   4%|▍         | 125/3120 [01:54<37:24,  1.33it/s]
Qwen2-VL train:   4%|▍         | 126/3120 [01:55<36:00,  1.39it/s]
Qwen2-VL train:   4%|▍         | 127/3120 [01:55<36:03,  1.38it/s]
Qwen2-VL train:   4%|▍         | 128/3120 [01:56<36:43,  1.36it/s]
Qwen2-VL train:   4%|▍         | 129/3120 [01:57<34:00,  1.47it/s]
Qwen2-VL train:   4%|▍         | 130/3120 [01:57<33:47,  1.48it/s]
Qwen2-VL train:   4%|▍         | 131/3120 [01:58<34:17,  1.45it/s]
Qwen2-VL train:   4%|▍         | 132/3120 [01:59<33:37,  1.48it/s]
Qwen2-VL train:   4%|▍         | 133/3120 [01:59<31:51,  1.56it/s]
Qwen2-VL train:   4%|▍         | 134/3120 [02:00<30:30,  1.63it/s]
Qwen2-VL train:   4%|▍         | 135/3120 [02:01<31:23,  1.59it/s]
Qwen2-VL train:   4%|▍         | 136/3120 [02:01<31:44,  1.57it/s]
Qwen2-VL train:   4%|▍         | 137/3120 [02:02<30:30,  1.63it/s]
Qwen2-VL train:   4%|▍         | 138/3120 [02:02<30:17,  1.64it/s]
Qwen2-VL train:   4%|▍         | 139/3120 [02:03<29:49,  1.67it/s]
Qwen2-VL train:   4%|▍         | 140/3120 [02:03<28:42,  1.73it/s]
Qwen2-VL train:   5%|▍         | 141/3120 [02:04<28:26,  1.75it/s]
Qwen2-VL train:   5%|▍         | 142/3120 [02:05<29:21,  1.69it/s]
Qwen2-VL train:   5%|▍         | 143/3120 [02:05<29:04,  1.71it/s]
Qwen2-VL train:   5%|▍         | 144/3120 [02:07<41:33,  1.19it/s]
Qwen2-VL train:   5%|▍         | 145/3120 [02:07<37:17,  1.33it/s]
Qwen2-VL train:   5%|▍         | 146/3120 [02:08<34:54,  1.42it/s]
Qwen2-VL train:   5%|▍         | 147/3120 [02:08<33:32,  1.48it/s]
Qwen2-VL train:   5%|▍         | 148/3120 [02:09<33:32,  1.48it/s]
Qwen2-VL train:   5%|▍         | 149/3120 [02:10<33:29,  1.48it/s]
Qwen2-VL train:   5%|▍         | 150/3120 [02:10<32:05,  1.54it/s]
Qwen2-VL train:   5%|▍         | 151/3120 [02:11<31:09,  1.59it/s]
Qwen2-VL train:   5%|▍         | 152/3120 [02:12<30:08,  1.64it/s]
Qwen2-VL train:   5%|▍         | 153/3120 [02:12<28:46,  1.72it/s]
Qwen2-VL train:   5%|▍         | 154/3120 [02:13<29:03,  1.70it/s]
Qwen2-VL train:   5%|▍         | 155/3120 [02:13<29:00,  1.70it/s]
Qwen2-VL train:   5%|▌         | 156/3120 [02:14<29:34,  1.67it/s]
Qwen2-VL train:   5%|▌         | 157/3120 [02:14<29:47,  1.66it/s]
Qwen2-VL train:   5%|▌         | 158/3120 [02:15<28:30,  1.73it/s]
Qwen2-VL train:   5%|▌         | 159/3120 [02:16<29:37,  1.67it/s]
Qwen2-VL train:   5%|▌         | 160/3120 [02:16<29:27,  1.67it/s]
Qwen2-VL train:   5%|▌         | 161/3120 [02:17<28:33,  1.73it/s]
Qwen2-VL train:   5%|▌         | 162/3120 [02:17<28:54,  1.71it/s]
Qwen2-VL train:   5%|▌         | 163/3120 [02:19<39:09,  1.26it/s]
Qwen2-VL train:   5%|▌         | 164/3120 [02:20<46:22,  1.06it/s]
Qwen2-VL train:   5%|▌         | 165/3120 [02:21<41:29,  1.19it/s]
Qwen2-VL train:   5%|▌         | 166/3120 [02:21<37:27,  1.31it/s]
Qwen2-VL train:   5%|▌         | 167/3120 [02:22<37:09,  1.32it/s]
Qwen2-VL train:   5%|▌         | 168/3120 [02:23<50:21,  1.02s/it]
Qwen2-VL train:   5%|▌         | 169/3120 [02:24<43:43,  1.12it/s]
Qwen2-VL train:   5%|▌         | 170/3120 [02:25<49:59,  1.02s/it]
Qwen2-VL train:   5%|▌         | 171/3120 [02:26<43:57,  1.12it/s]
Qwen2-VL train:   6%|▌         | 172/3120 [02:26<37:59,  1.29it/s]
Qwen2-VL train:   6%|▌         | 173/3120 [02:27<36:21,  1.35it/s]
Qwen2-VL train:   6%|▌         | 174/3120 [02:28<34:02,  1.44it/s]
Qwen2-VL train:   6%|▌         | 175/3120 [02:28<32:05,  1.53it/s]
Qwen2-VL train:   6%|▌         | 176/3120 [02:29<30:05,  1.63it/s]
Qwen2-VL train:   6%|▌         | 177/3120 [02:30<31:56,  1.54it/s]
Qwen2-VL train:   6%|▌         | 178/3120 [02:30<32:02,  1.53it/s]
Qwen2-VL train:   6%|▌         | 179/3120 [02:31<31:47,  1.54it/s]
Qwen2-VL train:   6%|▌         | 180/3120 [02:31<30:45,  1.59it/s]
Qwen2-VL train:   6%|▌         | 181/3120 [02:32<30:42,  1.60it/s]
Qwen2-VL train:   6%|▌         | 182/3120 [02:33<28:54,  1.69it/s]
Qwen2-VL train:   6%|▌         | 183/3120 [02:34<45:59,  1.06it/s]
Qwen2-VL train:   6%|▌         | 184/3120 [02:36<54:12,  1.11s/it]
Qwen2-VL train:   6%|▌         | 185/3120 [02:37<48:22,  1.01it/s]
Qwen2-VL train:   6%|▌         | 186/3120 [02:37<43:09,  1.13it/s]
Qwen2-VL train:   6%|▌         | 187/3120 [02:38<38:32,  1.27it/s]
Qwen2-VL train:   6%|▌         | 188/3120 [02:38<38:11,  1.28it/s]
Qwen2-VL train:   6%|▌         | 189/3120 [02:39<35:06,  1.39it/s]
Qwen2-VL train:   6%|▌         | 190/3120 [02:41<45:50,  1.07it/s]
Qwen2-VL train:   6%|▌         | 191/3120 [02:41<42:23,  1.15it/s]
Qwen2-VL train:   6%|▌         | 192/3120 [02:42<36:17,  1.34it/s]
Qwen2-VL train:   6%|▌         | 193/3120 [02:42<35:33,  1.37it/s]
Qwen2-VL train:   6%|▌         | 194/3120 [02:43<36:28,  1.34it/s]
Qwen2-VL train:   6%|▋         | 195/3120 [02:44<35:22,  1.38it/s]
Qwen2-VL train:   6%|▋         | 196/3120 [02:45<35:14,  1.38it/s]
Qwen2-VL train:   6%|▋         | 197/3120 [02:45<33:35,  1.45it/s]
Qwen2-VL train:   6%|▋         | 198/3120 [02:46<42:21,  1.15it/s]
Qwen2-VL train:   6%|▋         | 199/3120 [02:48<55:02,  1.13s/it]
Qwen2-VL train:   6%|▋         | 200/3120 [02:50<1:03:15,  1.30s/it]
Qwen2-VL train:   6%|▋         | 201/3120 [02:51<54:05,  1.11s/it]
Qwen2-VL train:   6%|▋         | 202/3120 [02:51<47:20,  1.03it/s]
Qwen2-VL train:   7%|▋         | 203/3120 [02:52<42:54,  1.13it/s]
Qwen2-VL train:   7%|▋         | 204/3120 [02:53<39:28,  1.23it/s]
Qwen2-VL train:   7%|▋         | 205/3120 [02:53<35:28,  1.37it/s]
Qwen2-VL train:   7%|▋         | 206/3120 [02:54<34:23,  1.41it/s]
Qwen2-VL train:   7%|▋         | 207/3120 [02:54<32:44,  1.48it/s]
Qwen2-VL train:   7%|▋         | 208/3120 [02:55<30:36,  1.59it/s]
Qwen2-VL train:   7%|▋         | 209/3120 [02:55<30:58,  1.57it/s]
Qwen2-VL train:   7%|▋         | 210/3120 [02:56<31:20,  1.55it/s]
Qwen2-VL train:   7%|▋         | 211/3120 [02:57<30:07,  1.61it/s]
Qwen2-VL train:   7%|▋         | 212/3120 [02:57<28:52,  1.68it/s]
Qwen2-VL train:   7%|▋         | 213/3120 [02:58<29:16,  1.65it/s]
Qwen2-VL train:   7%|▋         | 214/3120 [02:59<30:22,  1.59it/s]
Qwen2-VL train:   7%|▋         | 215/3120 [02:59<30:35,  1.58it/s]
Qwen2-VL train:   7%|▋         | 216/3120 [03:00<32:14,  1.50it/s]
Qwen2-VL train:   7%|▋         | 217/3120 [03:01<32:07,  1.51it/s]
Qwen2-VL train:   7%|▋         | 218/3120 [03:01<32:56,  1.47it/s]
Qwen2-VL train:   7%|▋         | 219/3120 [03:02<33:17,  1.45it/s]
Qwen2-VL train:   7%|▋         | 220/3120 [03:03<34:21,  1.41it/s]
Qwen2-VL train:   7%|▋         | 221/3120 [03:03<34:03,  1.42it/s]
Qwen2-VL train:   7%|▋         | 222/3120 [03:04<32:44,  1.48it/s]
Qwen2-VL train:   7%|▋         | 223/3120 [03:05<32:44,  1.47it/s]
Qwen2-VL train:   7%|▋         | 224/3120 [03:05<32:38,  1.48it/s]
Qwen2-VL train:   7%|▋         | 225/3120 [03:06<31:39,  1.52it/s]
Qwen2-VL train:   7%|▋         | 226/3120 [03:07<30:07,  1.60it/s]
Qwen2-VL train:   7%|▋         | 227/3120 [03:07<29:06,  1.66it/s]
Qwen2-VL train:   7%|▋         | 228/3120 [03:08<29:01,  1.66it/s]
Qwen2-VL train:   7%|▋         | 229/3120 [03:08<30:12,  1.59it/s]
Qwen2-VL train:   7%|▋         | 230/3120 [03:09<29:37,  1.63it/s]
Qwen2-VL train:   7%|▋         | 231/3120 [03:10<29:54,  1.61it/s]
Qwen2-VL train:   7%|▋         | 232/3120 [03:10<30:44,  1.57it/s]
Qwen2-VL train:   7%|▋         | 233/3120 [03:11<30:17,  1.59it/s]
Qwen2-VL train:   8%|▊         | 234/3120 [03:12<30:32,  1.57it/s]
Qwen2-VL train:   8%|▊         | 235/3120 [03:12<29:59,  1.60it/s]
Qwen2-VL train:   8%|▊         | 236/3120 [03:13<29:56,  1.61it/s]
Qwen2-VL train:   8%|▊         | 237/3120 [03:14<30:44,  1.56it/s]
Qwen2-VL train:   8%|▊         | 238/3120 [03:14<29:01,  1.65it/s]
Qwen2-VL train:   8%|▊         | 239/3120 [03:15<27:39,  1.74it/s]
Qwen2-VL train:   8%|▊         | 240/3120 [03:15<29:48,  1.61it/s]
Qwen2-VL train:   8%|▊         | 241/3120 [03:16<29:35,  1.62it/s]
Qwen2-VL train:   8%|▊         | 242/3120 [03:17<31:42,  1.51it/s]
Qwen2-VL train:   8%|▊         | 243/3120 [03:17<31:09,  1.54it/s]
Qwen2-VL train:   8%|▊         | 244/3120 [03:18<33:42,  1.42it/s]
Qwen2-VL train:   8%|▊         | 245/3120 [03:19<34:33,  1.39it/s]
Qwen2-VL train:   8%|▊         | 246/3120 [03:20<41:36,  1.15it/s]
Qwen2-VL train:   8%|▊         | 247/3120 [03:21<38:35,  1.24it/s]
Qwen2-VL train:   8%|▊         | 248/3120 [03:21<36:31,  1.31it/s]
Qwen2-VL train:   8%|▊         | 249/3120 [03:22<33:53,  1.41it/s]
Qwen2-VL train:   8%|▊         | 250/3120 [03:23<32:44,  1.46it/s]
Qwen2-VL train:   8%|▊         | 251/3120 [03:23<32:33,  1.47it/s]
Qwen2-VL train:   8%|▊         | 252/3120 [03:24<32:22,  1.48it/s]
Qwen2-VL train:   8%|▊         | 253/3120 [03:25<32:18,  1.48it/s]
Qwen2-VL train:   8%|▊         | 254/3120 [03:26<43:22,  1.10it/s]
Qwen2-VL train:   8%|▊         | 255/3120 [03:27<43:29,  1.10it/s]
Qwen2-VL train:   8%|▊         | 256/3120 [03:28<39:54,  1.20it/s]
Qwen2-VL train:   8%|▊         | 257/3120 [03:28<36:55,  1.29it/s]
Qwen2-VL train:   8%|▊         | 258/3120 [03:29<36:07,  1.32it/s]
Qwen2-VL train:   8%|▊         | 259/3120 [03:30<33:45,  1.41it/s]
Qwen2-VL train:   8%|▊         | 260/3120 [03:30<32:42,  1.46it/s]
Qwen2-VL train:   8%|▊         | 261/3120 [03:31<31:26,  1.52it/s]
Qwen2-VL train:   8%|▊         | 262/3120 [03:31<31:38,  1.51it/s]
Qwen2-VL train:   8%|▊         | 263/3120 [03:32<30:53,  1.54it/s]
Qwen2-VL train:   8%|▊         | 264/3120 [03:33<39:54,  1.19it/s]
Qwen2-VL train:   8%|▊         | 265/3120 [03:34<36:18,  1.31it/s]
Qwen2-VL train:   9%|▊         | 266/3120 [03:35<33:45,  1.41it/s]
Qwen2-VL train:   9%|▊         | 267/3120 [03:35<32:32,  1.46it/s]
Qwen2-VL train:   9%|▊         | 268/3120 [03:36<32:33,  1.46it/s]
Qwen2-VL train:   9%|▊         | 269/3120 [03:36<31:40,  1.50it/s]
Qwen2-VL train:   9%|▊         | 270/3120 [03:37<28:43,  1.65it/s]
Qwen2-VL train:   9%|▊         | 271/3120 [03:38<30:26,  1.56it/s]
Qwen2-VL train:   9%|▊         | 272/3120 [03:39<33:56,  1.40it/s]
Qwen2-VL train:   9%|▉         | 273/3120 [03:39<34:04,  1.39it/s]
Qwen2-VL train:   9%|▉         | 274/3120 [03:40<33:47,  1.40it/s]
Qwen2-VL train:   9%|▉         | 275/3120 [03:41<33:06,  1.43it/s]
Qwen2-VL train:   9%|▉         | 276/3120 [03:41<34:48,  1.36it/s]
Qwen2-VL train:   9%|▉         | 277/3120 [03:42<33:36,  1.41it/s]
Qwen2-VL train:   9%|▉         | 278/3120 [03:43<33:52,  1.40it/s]
Qwen2-VL train:   9%|▉         | 279/3120 [03:44<35:16,  1.34it/s]
Qwen2-VL train:   9%|▉         | 280/3120 [03:44<33:07,  1.43it/s]
Qwen2-VL train:   9%|▉         | 281/3120 [03:45<30:35,  1.55it/s]
Qwen2-VL train:   9%|▉         | 282/3120 [03:45<29:35,  1.60it/s]
Qwen2-VL train:   9%|▉         | 283/3120 [03:47<38:55,  1.21it/s]
Qwen2-VL train:   9%|▉         | 284/3120 [03:47<36:38,  1.29it/s]
Qwen2-VL train:   9%|▉         | 285/3120 [03:48<34:24,  1.37it/s]
Qwen2-VL train:   9%|▉         | 286/3120 [03:49<35:52,  1.32it/s]
Qwen2-VL train:   9%|▉         | 287/3120 [03:49<32:50,  1.44it/s]
Qwen2-VL train:   9%|▉         | 288/3120 [03:50<30:38,  1.54it/s]
Qwen2-VL train:   9%|▉         | 289/3120 [03:51<31:02,  1.52it/s]
Qwen2-VL train:   9%|▉         | 290/3120 [03:52<43:35,  1.08it/s]
Qwen2-VL train:   9%|▉         | 291/3120 [03:53<38:29,  1.23it/s]
Qwen2-VL train:   9%|▉         | 292/3120 [03:54<49:42,  1.05s/it]
Qwen2-VL train:   9%|▉         | 293/3120 [03:55<43:40,  1.08it/s]
Qwen2-VL train:   9%|▉         | 294/3120 [03:56<48:41,  1.03s/it]
Qwen2-VL train:   9%|▉         | 295/3120 [03:57<40:48,  1.15it/s]
Qwen2-VL train:   9%|▉         | 296/3120 [03:57<36:25,  1.29it/s]
Qwen2-VL train:  10%|▉         | 297/3120 [03:58<33:22,  1.41it/s]
Qwen2-VL train:  10%|▉         | 298/3120 [03:58<30:17,  1.55it/s]

===== SUMMARY =====
split  samples  exact_match      cer      wer
train     3120     0.261538 0.532114 0.792722
  val      780     0.285897 0.604268 0.803797
 test      780     0.270513 0.493699 0.762025
Saved: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train.csv
Saved: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val.csv
Saved: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test.csv
Saved: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_all_splits.csv
Saved: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_metrics_summary.csv

In [ ]:
import os
import pandas as pd
from tqdm import tqdm

def ensure_cols(df):
    df = df.copy()
    df["IMAGE"] = df["IMAGE"].astype(str)
    df["MEDICINE_NAME"] = df["MEDICINE_NAME"].astype(str)
    return df

def load_existing_preds(path):
    if os.path.exists(path):
        return pd.read_csv(path)
    return None

def evaluate_split_resumable(
    df: pd.DataFrame,
    split_name: str,
    limit: int | None = None,
    chunk_size: int = 300,
    save_every: int = 50
):
    """
    Writes/updates:
      BASE_FOLDER/qwen2vl_predictions_{split}_partial.csv
    Returns:
      path to partial csv
    """
    df = ensure_cols(df)
    if limit is not None:
        df = df.iloc[:limit].copy()

    partial_csv = os.path.join(BASE_FOLDER, f"qwen2vl_predictions_{split_name}_partial.csv")

    existing = load_existing_preds(partial_csv)
    done_images = set()
    if existing is not None and "IMAGE" in existing.columns:
        done_images = set(existing["IMAGE"].astype(str).tolist())
        print(f"✅ Resuming {split_name}: found {len(done_images)} already predicted rows.")


    remaining = df[~df["IMAGE"].isin(done_images)].copy()
    if len(remaining) == 0:
        print(f"✅ {split_name}: nothing left to predict.")
        return partial_csv

    rows_to_append = []
    processed = 0

    for chunk_start in range(0, len(remaining), chunk_size):
        chunk = remaining.iloc[chunk_start:chunk_start + chunk_size].copy()

        print(f"\n--- {split_name} chunk {chunk_start} → {chunk_start + len(chunk)} (of {len(remaining)}) ---")

        for idx, row in tqdm(chunk.iterrows(), total=len(chunk), desc=f"Qwen2-VL {split_name}"):
            img_name = row["IMAGE"]
            gt = row["MEDICINE_NAME"]

            img = load_rgb(img_name, split_name)
            pred_raw = qwen2vl_ocr_one(img)

            rec = {
                "split": split_name,
                "IMAGE": img_name,
                "MEDICINE_NAME": gt,
                "pred_raw": pred_raw,
                "pred_norm": normalize_text(pred_raw),
                "gt_norm": normalize_text(gt),
            }
            rows_to_append.append(rec)
            processed += 1


            if processed % save_every == 0:
                append_df = pd.DataFrame(rows_to_append)
                if os.path.exists(partial_csv):
                    append_df.to_csv(partial_csv, mode="a", header=False, index=False)
                else:
                    append_df.to_csv(partial_csv, index=False)
                rows_to_append = []
                print(f"💾 Saved progress: {processed} new rows -> {partial_csv}")


        if rows_to_append:
            append_df = pd.DataFrame(rows_to_append)
            if os.path.exists(partial_csv):
                append_df.to_csv(partial_csv, mode="a", header=False, index=False)
            else:
                append_df.to_csv(partial_csv, index=False)
            rows_to_append = []
            print(f"💾 Saved chunk -> {partial_csv}")

    print(f"✅ Done predicting split {split_name}. Output: {partial_csv}")
    return partial_csv

In [ ]:
LIMIT = None
CHUNK_SIZE = 300
SAVE_EVERY = 25

train_csv = evaluate_split_resumable(df_train, "train", limit=LIMIT, chunk_size=CHUNK_SIZE, save_every=SAVE_EVERY)
val_csv   = evaluate_split_resumable(df_val,   "val",   limit=LIMIT, chunk_size=CHUNK_SIZE, save_every=SAVE_EVERY)
test_csv  = evaluate_split_resumable(df_test,  "test",  limit=LIMIT, chunk_size=CHUNK_SIZE, save_every=SAVE_EVERY)

--- train chunk 0 → 300 (of 3120) ---

Qwen2-VL train:   8%|▊         | 25/300 [00:10<01:46,  2.58it/s]

💾 Saved progress: 25 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  17%|█▋        | 50/300 [00:24<02:14,  1.86it/s]

💾 Saved progress: 50 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  25%|██▌       | 76/300 [00:32<00:38,  5.87it/s]

💾 Saved progress: 75 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  34%|███▎      | 101/300 [00:44<01:48,  1.84it/s]

💾 Saved progress: 100 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▏     | 125/300 [01:00<01:15,  2.31it/s]

💾 Saved progress: 125 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  50%|█████     | 150/300 [01:06<00:38,  3.90it/s]

💾 Saved progress: 150 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  59%|█████▊    | 176/300 [01:17<00:33,  3.74it/s]

💾 Saved progress: 175 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  67%|██████▋   | 200/300 [01:28<01:10,  1.41it/s]

💾 Saved progress: 200 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  75%|███████▌  | 225/300 [01:35<00:27,  2.68it/s]

💾 Saved progress: 225 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  83%|████████▎ | 250/300 [01:44<00:17,  2.86it/s]

💾 Saved progress: 250 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  92%|█████████▏| 275/300 [01:53<00:08,  3.03it/s]

💾 Saved progress: 275 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 300/300 [02:07<00:00,  2.35it/s]

💾 Saved progress: 300 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- train chunk 300 → 600 (of 3120) ---

Qwen2-VL train:   9%|▊         | 26/300 [00:19<05:28,  1.20s/it]

💾 Saved progress: 325 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  17%|█▋        | 50/300 [00:34<02:46,  1.50it/s]

💾 Saved progress: 350 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  25%|██▌       | 76/300 [00:42<01:02,  3.61it/s]

💾 Saved progress: 375 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  34%|███▎      | 101/300 [00:48<00:48,  4.10it/s]

💾 Saved progress: 400 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▏     | 125/300 [00:54<00:58,  3.02it/s]

💾 Saved progress: 425 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  50%|█████     | 150/300 [01:00<00:39,  3.78it/s]

💾 Saved progress: 450 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  58%|█████▊    | 175/300 [01:11<00:33,  3.73it/s]

💾 Saved progress: 475 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  67%|██████▋   | 200/300 [01:19<00:27,  3.65it/s]

💾 Saved progress: 500 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  75%|███████▌  | 225/300 [01:25<00:18,  4.15it/s]

💾 Saved progress: 525 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  83%|████████▎ | 250/300 [01:32<00:17,  2.92it/s]

💾 Saved progress: 550 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  92%|█████████▏| 276/300 [01:44<00:08,  2.78it/s]

💾 Saved progress: 575 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 300/300 [01:52<00:00,  2.66it/s]

💾 Saved progress: 600 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- train chunk 600 → 900 (of 3120) ---

Qwen2-VL train:   8%|▊         | 25/300 [00:09<01:29,  3.06it/s]

💾 Saved progress: 625 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  17%|█▋        | 50/300 [00:17<01:10,  3.55it/s]

💾 Saved progress: 650 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  25%|██▌       | 75/300 [00:27<01:18,  2.88it/s]

💾 Saved progress: 675 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  33%|███▎      | 100/300 [00:34<00:46,  4.26it/s]

💾 Saved progress: 700 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▏     | 125/300 [00:42<00:42,  4.07it/s]

💾 Saved progress: 725 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  50%|█████     | 150/300 [00:50<00:52,  2.88it/s]

💾 Saved progress: 750 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  58%|█████▊    | 175/300 [00:58<00:28,  4.40it/s]

💾 Saved progress: 775 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  67%|██████▋   | 200/300 [01:04<00:27,  3.61it/s]

💾 Saved progress: 800 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  75%|███████▌  | 225/300 [01:10<00:16,  4.66it/s]

💾 Saved progress: 825 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  83%|████████▎ | 250/300 [01:16<00:13,  3.84it/s]

💾 Saved progress: 850 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  92%|█████████▏| 276/300 [01:23<00:05,  4.29it/s]

💾 Saved progress: 875 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 300/300 [01:32<00:00,  3.26it/s]

💾 Saved progress: 900 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- train chunk 900 → 1200 (of 3120) ---

Qwen2-VL train:   8%|▊         | 25/300 [00:08<01:28,  3.12it/s]

💾 Saved progress: 925 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  17%|█▋        | 50/300 [00:17<01:31,  2.74it/s]

💾 Saved progress: 950 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  25%|██▌       | 75/300 [00:24<00:51,  4.37it/s]

💾 Saved progress: 975 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  33%|███▎      | 100/300 [00:32<00:44,  4.54it/s]

💾 Saved progress: 1000 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▏     | 125/300 [00:39<00:42,  4.10it/s]

💾 Saved progress: 1025 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  50%|█████     | 150/300 [00:48<00:36,  4.05it/s]

💾 Saved progress: 1050 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  58%|█████▊    | 175/300 [00:55<00:35,  3.48it/s]

💾 Saved progress: 1075 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  67%|██████▋   | 200/300 [01:04<00:25,  3.93it/s]

💾 Saved progress: 1100 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  75%|███████▌  | 225/300 [01:16<00:35,  2.09it/s]

💾 Saved progress: 1125 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  83%|████████▎ | 250/300 [01:35<00:32,  1.54it/s]

💾 Saved progress: 1150 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  92%|█████████▏| 275/300 [01:44<00:07,  3.50it/s]

💾 Saved progress: 1175 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 300/300 [01:54<00:00,  2.63it/s]

💾 Saved progress: 1200 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- train chunk 1200 → 1500 (of 3120) ---

Qwen2-VL train:   8%|▊         | 25/300 [00:09<03:08,  1.46it/s]

💾 Saved progress: 1225 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  17%|█▋        | 50/300 [00:19<01:21,  3.05it/s]

💾 Saved progress: 1250 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  25%|██▌       | 75/300 [00:28<01:16,  2.92it/s]

💾 Saved progress: 1275 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  33%|███▎      | 100/300 [00:37<01:03,  3.14it/s]

💾 Saved progress: 1300 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▏     | 126/300 [00:45<00:33,  5.12it/s]

💾 Saved progress: 1325 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  50%|█████     | 151/300 [00:54<01:06,  2.26it/s]

💾 Saved progress: 1350 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  58%|█████▊    | 175/300 [01:09<01:44,  1.20it/s]

💾 Saved progress: 1375 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  67%|██████▋   | 200/300 [01:24<01:29,  1.12it/s]

💾 Saved progress: 1400 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  75%|███████▌  | 225/300 [01:31<00:31,  2.36it/s]

💾 Saved progress: 1425 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  83%|████████▎ | 250/300 [01:41<00:12,  3.87it/s]

💾 Saved progress: 1450 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  92%|█████████▏| 275/300 [01:48<00:08,  2.94it/s]

💾 Saved progress: 1475 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 300/300 [02:05<00:00,  2.40it/s]

💾 Saved progress: 1500 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- train chunk 1500 → 1800 (of 3120) ---

Qwen2-VL train:   8%|▊         | 25/300 [00:14<01:14,  3.69it/s]

💾 Saved progress: 1525 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  17%|█▋        | 50/300 [00:21<01:00,  4.13it/s]

💾 Saved progress: 1550 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  25%|██▌       | 76/300 [00:29<00:53,  4.21it/s]

💾 Saved progress: 1575 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  33%|███▎      | 100/300 [00:35<01:08,  2.93it/s]

💾 Saved progress: 1600 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▏     | 125/300 [00:51<01:59,  1.46it/s]

💾 Saved progress: 1625 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  50%|█████     | 150/300 [01:08<01:12,  2.06it/s]

💾 Saved progress: 1650 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  58%|█████▊    | 175/300 [01:25<01:09,  1.79it/s]

💾 Saved progress: 1675 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  67%|██████▋   | 200/300 [01:36<00:41,  2.39it/s]

💾 Saved progress: 1700 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  75%|███████▌  | 225/300 [01:44<00:23,  3.13it/s]

💾 Saved progress: 1725 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  83%|████████▎ | 250/300 [01:51<00:13,  3.82it/s]

💾 Saved progress: 1750 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  92%|█████████▏| 275/300 [02:05<00:17,  1.41it/s]

💾 Saved progress: 1775 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 300/300 [02:17<00:00,  2.18it/s]

💾 Saved progress: 1800 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- train chunk 1800 → 2100 (of 3120) ---

Qwen2-VL train:   8%|▊         | 25/300 [00:13<01:22,  3.32it/s]

💾 Saved progress: 1825 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  17%|█▋        | 51/300 [00:26<01:00,  4.10it/s]

💾 Saved progress: 1850 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  25%|██▌       | 75/300 [00:31<00:59,  3.78it/s]

💾 Saved progress: 1875 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  33%|███▎      | 100/300 [00:42<00:52,  3.82it/s]

💾 Saved progress: 1900 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▏     | 125/300 [00:58<00:35,  4.96it/s]

💾 Saved progress: 1925 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  50%|█████     | 151/300 [01:08<00:25,  5.91it/s]

💾 Saved progress: 1950 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  58%|█████▊    | 175/300 [01:13<00:29,  4.20it/s]

💾 Saved progress: 1975 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  67%|██████▋   | 201/300 [01:20<00:23,  4.23it/s]

💾 Saved progress: 2000 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  75%|███████▌  | 225/300 [01:29<00:25,  2.90it/s]

💾 Saved progress: 2025 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  84%|████████▎ | 251/300 [01:38<00:18,  2.71it/s]

💾 Saved progress: 2050 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  92%|█████████▏| 275/300 [01:48<00:13,  1.86it/s]

💾 Saved progress: 2075 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 300/300 [01:55<00:00,  2.60it/s]

💾 Saved progress: 2100 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- train chunk 2100 → 2400 (of 3120) ---

Qwen2-VL train:   9%|▊         | 26/300 [00:07<01:07,  4.04it/s]

💾 Saved progress: 2125 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  17%|█▋        | 51/300 [00:14<00:56,  4.43it/s]

💾 Saved progress: 2150 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  25%|██▌       | 75/300 [00:22<01:07,  3.35it/s]

💾 Saved progress: 2175 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  33%|███▎      | 100/300 [00:31<01:14,  2.69it/s]

💾 Saved progress: 2200 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▏     | 126/300 [00:38<00:55,  3.12it/s]

💾 Saved progress: 2225 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  50%|█████     | 150/300 [00:46<00:49,  3.02it/s]

💾 Saved progress: 2250 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  58%|█████▊    | 175/300 [00:54<00:44,  2.79it/s]

💾 Saved progress: 2275 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  67%|██████▋   | 200/300 [01:03<00:27,  3.66it/s]

💾 Saved progress: 2300 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  75%|███████▌  | 225/300 [01:14<00:56,  1.32it/s]

💾 Saved progress: 2325 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  83%|████████▎ | 250/300 [01:32<00:31,  1.60it/s]

💾 Saved progress: 2350 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  92%|█████████▏| 276/300 [01:45<00:06,  3.98it/s]

💾 Saved progress: 2375 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 300/300 [01:58<00:00,  2.54it/s]

💾 Saved progress: 2400 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- train chunk 2400 → 2700 (of 3120) ---

Qwen2-VL train:   8%|▊         | 25/300 [00:05<00:55,  4.94it/s]

💾 Saved progress: 2425 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  17%|█▋        | 50/300 [00:14<02:22,  1.76it/s]

💾 Saved progress: 2450 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  25%|██▌       | 75/300 [00:25<01:49,  2.06it/s]

💾 Saved progress: 2475 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  34%|███▎      | 101/300 [00:33<00:35,  5.55it/s]

💾 Saved progress: 2500 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▏     | 125/300 [00:40<01:03,  2.74it/s]

💾 Saved progress: 2525 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  50%|█████     | 150/300 [00:48<01:06,  2.27it/s]

💾 Saved progress: 2550 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  58%|█████▊    | 175/300 [00:55<00:29,  4.26it/s]

💾 Saved progress: 2575 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  67%|██████▋   | 200/300 [01:02<00:24,  4.01it/s]

💾 Saved progress: 2600 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  75%|███████▌  | 226/300 [01:10<00:15,  4.78it/s]

💾 Saved progress: 2625 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  83%|████████▎ | 250/300 [01:20<00:17,  2.88it/s]

💾 Saved progress: 2650 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  92%|█████████▏| 275/300 [01:28<00:06,  4.09it/s]

💾 Saved progress: 2675 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 300/300 [01:39<00:00,  3.01it/s]

💾 Saved progress: 2700 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- train chunk 2700 → 3000 (of 3120) ---

Qwen2-VL train:   8%|▊         | 25/300 [00:08<02:45,  1.66it/s]

💾 Saved progress: 2725 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  17%|█▋        | 50/300 [00:17<02:01,  2.06it/s]

💾 Saved progress: 2750 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  25%|██▌       | 75/300 [00:28<02:11,  1.72it/s]

💾 Saved progress: 2775 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  34%|███▎      | 101/300 [00:38<01:45,  1.88it/s]

💾 Saved progress: 2800 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▏     | 125/300 [00:43<00:39,  4.47it/s]

💾 Saved progress: 2825 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  50%|█████     | 150/300 [00:51<00:41,  3.63it/s]

💾 Saved progress: 2850 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  58%|█████▊    | 175/300 [00:58<00:45,  2.76it/s]

💾 Saved progress: 2875 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  67%|██████▋   | 200/300 [01:18<01:04,  1.56it/s]

💾 Saved progress: 2900 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  75%|███████▌  | 226/300 [01:26<00:18,  4.09it/s]

💾 Saved progress: 2925 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  83%|████████▎ | 250/300 [01:36<00:22,  2.22it/s]

💾 Saved progress: 2950 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  92%|█████████▏| 275/300 [01:47<00:13,  1.80it/s]

💾 Saved progress: 2975 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 300/300 [02:00<00:00,  2.49it/s]

💾 Saved progress: 3000 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- train chunk 3000 → 3120 (of 3120) ---

Qwen2-VL train:  21%|██        | 25/120 [00:14<00:50,  1.89it/s]

💾 Saved progress: 3025 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  42%|████▎     | 51/120 [00:32<00:18,  3.67it/s]

💾 Saved progress: 3050 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  62%|██████▎   | 75/120 [00:39<00:27,  1.66it/s]

💾 Saved progress: 3075 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train:  83%|████████▎ | 100/120 [00:52<00:21,  1.05s/it]

💾 Saved progress: 3100 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

Qwen2-VL train: 100%|██████████| 120/120 [01:03<00:00,  1.90it/s]

💾 Saved chunk -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv
✅ Done predicting split train. Output: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train_partial.csv

--- val chunk 0 → 300 (of 780) ---

Qwen2-VL val:   8%|▊         | 25/300 [00:10<03:30,  1.31it/s]

💾 Saved progress: 25 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  17%|█▋        | 51/300 [00:23<01:27,  2.85it/s]

💾 Saved progress: 50 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  25%|██▌       | 76/300 [00:33<01:59,  1.87it/s]

💾 Saved progress: 75 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  34%|███▎      | 101/300 [00:41<00:44,  4.47it/s]

💾 Saved progress: 100 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  42%|████▏     | 126/300 [00:48<00:38,  4.49it/s]

💾 Saved progress: 125 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  50%|█████     | 150/300 [00:54<00:37,  3.97it/s]

💾 Saved progress: 150 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  58%|█████▊    | 175/300 [01:09<00:32,  3.87it/s]

💾 Saved progress: 175 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  67%|██████▋   | 201/300 [01:17<00:21,  4.52it/s]

💾 Saved progress: 200 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  75%|███████▌  | 225/300 [01:22<00:21,  3.52it/s]

💾 Saved progress: 225 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  83%|████████▎ | 250/300 [01:30<00:13,  3.84it/s]

💾 Saved progress: 250 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  92%|█████████▏| 275/300 [01:41<00:11,  2.16it/s]

💾 Saved progress: 275 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val: 100%|██████████| 300/300 [01:52<00:00,  2.68it/s]

💾 Saved progress: 300 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

--- val chunk 300 → 600 (of 780) ---

Qwen2-VL val:   9%|▊         | 26/300 [00:09<01:06,  4.10it/s]

💾 Saved progress: 325 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  17%|█▋        | 50/300 [00:18<02:11,  1.91it/s]

💾 Saved progress: 350 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  25%|██▌       | 75/300 [00:29<03:07,  1.20it/s]

💾 Saved progress: 375 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  33%|███▎      | 100/300 [00:39<00:47,  4.24it/s]

💾 Saved progress: 400 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  42%|████▏     | 125/300 [00:57<02:42,  1.07it/s]

💾 Saved progress: 425 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  50%|█████     | 150/300 [01:13<02:27,  1.02it/s]

💾 Saved progress: 450 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  58%|█████▊    | 175/300 [01:27<01:07,  1.86it/s]

💾 Saved progress: 475 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  67%|██████▋   | 201/300 [01:33<00:22,  4.42it/s]

💾 Saved progress: 500 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  75%|███████▌  | 226/300 [01:43<00:18,  4.04it/s]

💾 Saved progress: 525 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  83%|████████▎ | 250/300 [01:48<00:13,  3.84it/s]

💾 Saved progress: 550 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  92%|█████████▏| 275/300 [01:57<00:06,  3.81it/s]

💾 Saved progress: 575 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val: 100%|██████████| 300/300 [02:10<00:00,  2.30it/s]

💾 Saved progress: 600 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

--- val chunk 600 → 780 (of 780) ---

Qwen2-VL val:  14%|█▍        | 26/180 [00:11<00:43,  3.53it/s]

💾 Saved progress: 625 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  28%|██▊       | 50/180 [00:18<00:29,  4.34it/s]

💾 Saved progress: 650 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  42%|████▏     | 76/180 [00:26<00:22,  4.66it/s]

💾 Saved progress: 675 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  56%|█████▌    | 100/180 [00:35<00:25,  3.11it/s]

💾 Saved progress: 700 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  69%|██████▉   | 125/180 [00:46<00:30,  1.78it/s]

💾 Saved progress: 725 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  83%|████████▎ | 150/180 [01:01<00:19,  1.52it/s]

💾 Saved progress: 750 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val:  97%|█████████▋| 175/180 [01:16<00:02,  2.30it/s]

💾 Saved progress: 775 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

Qwen2-VL val: 100%|██████████| 180/180 [01:17<00:00,  2.31it/s]

💾 Saved chunk -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv
✅ Done predicting split val. Output: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val_partial.csv

--- test chunk 0 → 300 (of 780) ---

Qwen2-VL test:   8%|▊         | 25/300 [00:15<07:30,  1.64s/it]

💾 Saved progress: 25 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  17%|█▋        | 50/300 [00:26<01:43,  2.40it/s]

💾 Saved progress: 50 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  25%|██▌       | 75/300 [00:35<01:36,  2.34it/s]

💾 Saved progress: 75 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  33%|███▎      | 100/300 [00:45<00:48,  4.09it/s]

💾 Saved progress: 100 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  42%|████▏     | 125/300 [00:51<00:42,  4.11it/s]

💾 Saved progress: 125 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  50%|█████     | 150/300 [01:01<01:36,  1.55it/s]

💾 Saved progress: 150 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  58%|█████▊    | 175/300 [01:10<01:11,  1.76it/s]

💾 Saved progress: 175 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  67%|██████▋   | 201/300 [01:17<00:30,  3.25it/s]

💾 Saved progress: 200 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  75%|███████▌  | 225/300 [01:24<00:33,  2.23it/s]

💾 Saved progress: 225 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  83%|████████▎ | 250/300 [01:30<00:10,  4.95it/s]

💾 Saved progress: 250 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  92%|█████████▏| 275/300 [01:36<00:08,  3.08it/s]

💾 Saved progress: 275 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test: 100%|██████████| 300/300 [01:46<00:00,  2.82it/s]

💾 Saved progress: 300 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

--- test chunk 300 → 600 (of 780) ---

Qwen2-VL test:   8%|▊         | 25/300 [00:15<02:02,  2.24it/s]

💾 Saved progress: 325 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  17%|█▋        | 50/300 [00:30<02:35,  1.60it/s]

💾 Saved progress: 350 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  25%|██▌       | 75/300 [00:38<01:36,  2.33it/s]

💾 Saved progress: 375 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  33%|███▎      | 100/300 [00:50<00:51,  3.86it/s]

💾 Saved progress: 400 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  42%|████▏     | 125/300 [01:00<00:56,  3.12it/s]

💾 Saved progress: 425 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  50%|█████     | 150/300 [01:09<01:04,  2.34it/s]

💾 Saved progress: 450 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  58%|█████▊    | 175/300 [01:20<00:31,  3.91it/s]

💾 Saved progress: 475 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  67%|██████▋   | 201/300 [01:30<00:34,  2.91it/s]

💾 Saved progress: 500 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  75%|███████▌  | 226/300 [01:38<00:17,  4.34it/s]

💾 Saved progress: 525 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  83%|████████▎ | 250/300 [01:46<00:22,  2.20it/s]

💾 Saved progress: 550 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  92%|█████████▏| 275/300 [01:55<00:14,  1.67it/s]

💾 Saved progress: 575 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test: 100%|██████████| 300/300 [02:05<00:00,  2.38it/s]

💾 Saved progress: 600 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

--- test chunk 600 → 780 (of 780) ---

Qwen2-VL test:  14%|█▍        | 26/180 [00:07<00:33,  4.55it/s]

💾 Saved progress: 625 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  28%|██▊       | 50/180 [00:13<00:28,  4.49it/s]

💾 Saved progress: 650 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  42%|████▏     | 76/180 [00:23<00:22,  4.64it/s]

💾 Saved progress: 675 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  56%|█████▌    | 100/180 [00:31<00:28,  2.85it/s]

💾 Saved progress: 700 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  69%|██████▉   | 125/180 [00:40<00:26,  2.05it/s]

💾 Saved progress: 725 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  83%|████████▎ | 150/180 [00:48<00:10,  2.88it/s]

💾 Saved progress: 750 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test:  97%|█████████▋| 175/180 [00:58<00:01,  3.36it/s]

💾 Saved progress: 775 new rows -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

Qwen2-VL test: 100%|██████████| 180/180 [00:59<00:00,  3.01it/s]

💾 Saved chunk -> /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv
✅ Done predicting split test. Output: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test_partial.csv

In [ ]:
import os
import pandas as pd
from jiwer import wer

def compute_metrics_from_csv(csv_path: str, split_name: str):
    if not csv_path or not os.path.exists(csv_path):
        print(f"[WARN] Missing file for {split_name}: {csv_path}")
        return None, None

    out = pd.read_csv(csv_path)

    out["IMAGE"] = out["IMAGE"].astype(str)
    out = out.drop_duplicates(subset=["IMAGE"], keep="last")

    exact_match = (out["pred_norm"] == out["gt_norm"]).mean()
    cer_value = cer_metric.compute(
        predictions=out["pred_norm"].astype(str).tolist(),
        references=out["gt_norm"].astype(str).tolist()
    )
    wer_value = wer(out["gt_norm"].astype(str).tolist(), out["pred_norm"].astype(str).tolist())

    metrics = {
        "split": split_name,
        "samples": int(len(out)),
        "exact_match": float(exact_match),
        "cer": float(cer_value),
        "wer": float(wer_value),
    }
    return metrics, out

all_metrics = []
all_outputs = []

for split_name in ["train", "val", "test"]:
    csv_path = os.path.join(BASE_FOLDER, f"qwen2vl_predictions_{split_name}_partial.csv")
    metrics, out = compute_metrics_from_csv(csv_path, split_name)
    if metrics is None:
        continue
    all_metrics.append(metrics)
    all_outputs.append(out)

metrics_df = pd.DataFrame(all_metrics)
print("\n===== FINAL SUMMARY =====")
print(metrics_df.to_string(index=False))


for out in all_outputs:
    split = out["split"].iloc[0]
    final_csv = os.path.join(BASE_FOLDER, f"qwen2vl_predictions_{split}.csv")
    out.to_csv(final_csv, index=False)
    print("Saved:", final_csv)

combined = pd.concat(all_outputs, ignore_index=True)
combined_csv = os.path.join(BASE_FOLDER, "qwen2vl_predictions_all_splits.csv")
combined.to_csv(combined_csv, index=False)
print("Saved:", combined_csv)

metrics_csv = os.path.join(BASE_FOLDER, "qwen2vl_metrics_summary.csv")
metrics_df.to_csv(metrics_csv, index=False)
print("Saved:", metrics_csv)

===== FINAL SUMMARY =====
split  samples  exact_match      cer      wer
train     3120     0.261538 0.532114 0.792722
  val      780     0.285897 0.604268 0.803797
 test      780     0.270513 0.493699 0.762025
Saved: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_train.csv
Saved: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_val.csv
Saved: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_test.csv
Saved: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_predictions_all_splits.csv
Saved: /content/drive/MyDrive/Mixed OCR/English Medical/Doctor’s Handwritten Prescription BD dataset/Doctor’s Handwritten Prescription BD dataset/qwen2vl_metrics_summary.csv